sudo: false

language: python

matrix:
  include:
    - python: pypy
      env: TOX_ENV=pypy-check,pypy-test,coverage
    - python: pypy3
      env: TOX_ENV=pypy3-check,pypy3-test,coverage
    - python: 2.6.9
      env: TOX_ENV=py26-check,py26-test,coverage
    - python: 2.7.11
      env: TOX_ENV=py27-check,py27-test,coverage
    - python: 3.3.6
      env: TOX_ENV=py33-check,py33-test,coverage
    - python: 3.4.4
      env: TOX_ENV=py34-check,py34-test,coverage
    - python: 3.5.1
      env: TOX_ENV=py35-check,py35-test,coverage
    - python: 3.6-dev
      env: TOX_ENV=py36-check,py36-test,coverage

install:
  - env | sort
  - ls -alF ~/virtualenv
  - python --version
  - pip install --upgrade pip setuptools tox coveralls

script:
  - tox -e $TOX_ENV
  - coveralls --rcfile=tox.ini
